#!/bin/bash


# On s'assure que le dossier log existe
mkdir -p logs

# Parcourt tous les dossiers commençant par FV_replica_
for dir in ams_* ; do
    if [ -d "$dir" ]; then
        echo "Accès au dossier : $dir"

        # Entre dans le dossier, lance ccc_msub, et revient au parent
        # Note : remplacez 'job_ini' par le nom de votre script de calcul
        (cd "$dir" && ccc_msub job_topaze)

        # Délai pour le scheduler
        sleep 0.2
    fi
done

echo "Toutes les soumissions sont terminées."
