#!/bin/bash

#MSUB -r submission_loop
#MSUB -o logs/out_%I
#MSUB -e logs/err_%I
#MSUB -q a100
#MSUB -Q normal
#MSUB -N 1
#MSUB -n 1
#MSUB -c 1
#MSUB -T 3600
#MSUB -m scratch,work

# On s'assure que le dossier log existe
mkdir -p logs

# Parcourt tous les dossiers AMS de ce theta.
for dir in ams_* ; do
    if [ -d "$dir" ]; then
        echo "Accès au dossier : $dir"

        # Entre dans le dossier, lance ccc_msub, et revient au parent
        # Note : remplacez 'job_ini' par le nom de votre script de calcul
        (cd "$dir" && ccc_msub job_topaze)

        # Délai pour le scheduler
        sleep 0.2
    fi
done

echo "Toutes les soumissions sont terminées."
