#!/bin/sh

#MSUB -r butane_ini_D
#MSUB -o logs/IniD_out%I
#MSUB -e logs/IniD_err%I
#MSUB -q a100  #partition, see "machine.info" comand
#MSUB -Q normal   #QOS see "machine.info" comand
#MSUB -N 1 # number of nodes
#MSUB -n 1
#MSUB -c 32       # number of cpu per tasks
#MSUB -T 86400    # time limit
#MSUB -m work,scratch  # accessible partitions

## python env
# source $SCRATCH/girsams_env/bin/activate

python compute_ini_D.py ${N_INI_CONDS:-100}
