#!/bin/bash
# Parcourt tous les dossiers commençant par FV_replica_
for dir in FV_replica_*/ ; do
    if [ -d "$dir" ]; then
        echo "Accès au dossier : $dir"
        
        # Entre dans le dossier, lance sbatch, et revient au parent
        (cd "$dir" && sbatch job)
        
        # Optionnel : petit délai pour ne pas saturer le scheduler Slurm
        sleep 0.5
    fi
done

echo "Toutes les soumissions sont terminées."
